Repository Hagustin/FlexPay, pull requests merged in 2025-01, with the labels that each got.

#52 Implement QR Code Payment System
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/graphql/resolvers.ts
  server/src/graphql/typeDefs.ts
  server/src/models/User.ts
Labels: enhancement

#78 added test to secure CORS + ReadME
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  README.md
  client/package.json
  client/src/components/transactions.tsx
  client/src/main.tsx
  package.json
  server/package.json
Labels: documentation

#80 UI styling
  client/public/bread.svg
  client/src/App.tsx
  client/src/components/navbar.tsx
  client/src/components/signIn.tsx
  client/src/components/signUp.tsx
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
  client/tailwind.config.js
Labels: enhancement

#84 missing navigational j.s effect
  client/src/components/navbar.tsx
  client/src/utils/auth.ts
Labels: bug
